# Default values for redis cluster.

# Must set an application name for the redis cluster script to work
appName: redis

replicaCount: 6
masterCount: 3
slaveCount: 3

image:
  repository: rivernet/redis
  tag: 3.0.1

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
